# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('A', 'Aberto'), ('E', 'Em andamento'), ('F', 'Fechado')], max_length=1)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
